"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const controllers_1 = require("../handlers/controllers");
const shopsRouter = (0, express_1.Router)();
shopsRouter.post('/items', controllers_1.shopsController.createItem);
shopsRouter.post("/orders", controllers_1.shopsController.createOrder);
shopsRouter.get("/items", controllers_1.shopsController.getItems);
shopsRouter.get("/orders", controllers_1.shopsController.getUserOrder);
shopsRouter.put("/orders", controllers_1.shopsController.changeOrderStatus);
exports.default = shopsRouter;
